/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Estoque;
import negocio.Funcionario;
import negocio.Venda;
import persistencia.EstoqueDAO;
import persistencia.FuncionarioDAO;
import persistencia.IEstoque;
import persistencia.IFuncionario;
import persistencia.VendaDAO;

/**
 *
 * @author Vinicius
 */
public class fmConsultaVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmConsultaVenda
     */
    private final IFuncionario dao = new FuncionarioDAO();
    private Funcionario funcionario = new Funcionario();

    private final IEstoque dao2 = new EstoqueDAO();
    Estoque estoque = new Estoque();

    private final VendaDAO dao3 = new VendaDAO();
    Venda venda = new Venda();

    public String nome;

    public void estoques() {
        this.cbEstoque.removeAllItems();
        List<Estoque> lista1 = dao2.listarTodos();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Estoque e : lista1) {
            modelo.addElement(e.getNomeProduto());
        }

        this.cbEstoque.setModel(modelo);
    }

    public void funcionario() {
        this.cbFuncionario.removeAllItems();
        List<Funcionario> lista2 = dao.listarTodos();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (Funcionario f : lista2) {
            modelo.addElement(f.getNome());
        }

        this.cbFuncionario.setModel(modelo);
    }

    public void mostrarLista() {
        estoques();
        funcionario();
        List<Venda> lista = dao3.listarTodos();
        DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
        modelo2.setNumRows(0);
        SimpleDateFormat DateFor = new SimpleDateFormat("dd/MM/yyyy");
        for (Venda pro : lista) {
            String stringDate = DateFor.format(pro.getData().getTime());
            funcionario = dao.getByID(pro.getIdFuncionario());
            estoque = dao2.getByID(pro.getIdEstoque());
//            System.out.println(pro.getIdFuncionario());
            modelo2.addRow(
                    new Object[]{pro.getIdVendas().toString(),
                        pro.getQuantidade().toString(),
                        pro.getValor().toString(),
                        stringDate,
                        estoque.getNomeProduto(),
                        funcionario.getNome()
                    });
        }
    }

    public fmConsultaVenda(String nome) {
        this.nome = nome;
        initComponents();
    }

    public boolean verificar(String valor, String quantidade, String data, String id) {

        if (data.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Data em branco na linha " + id);
            return false;
        }
        if (quantidade.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Quantidade em branco na linha " + id);
            return false;
        }
        if (valor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo valor em branco na linha " + id);
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelImagemLogin21 = new images.PainelImagemLogin2();
        jLabel1 = new javax.swing.JLabel();
        txtIDVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        cbFuncionario = new javax.swing.JComboBox<>();
        cbEstoque = new javax.swing.JComboBox<>();

        setTitle("Consulta de vendas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        painelImagemLogin21.setImg(new ImageIcon("src/images/imagem_Login.jpg"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("ID da Venda:");

        txtIDVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDVendaKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/shoppingcart_below_compra_12831.png"))); // NOI18N
        jLabel2.setText("Consulta de Venda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Quantidade", "Valor", "Data", "Produto", "Funcionario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setCellEditor(null);
            jTable1.getColumnModel().getColumn(4).setCellEditor(new javax.swing.DefaultCellEditor(cbEstoque)

            );
            jTable1.getColumnModel().getColumn(5).setCellEditor(new javax.swing.DefaultCellEditor(cbFuncionario)

            );
        }

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(0, 0, 255));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/file_new_22051.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(0, 0, 255));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/save_21411.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(0, 0, 255));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Button-Red-Cancel-icon.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 0, 255));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/SignOut_icon-icons.com_74704.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEstoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout painelImagemLogin21Layout = new javax.swing.GroupLayout(painelImagemLogin21);
        painelImagemLogin21.setLayout(painelImagemLogin21Layout);
        painelImagemLogin21Layout.setHorizontalGroup(
            painelImagemLogin21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelImagemLogin21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(74, 74, 74)
                .addGroup(painelImagemLogin21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(174, 174, 174))
            .addGroup(painelImagemLogin21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelImagemLogin21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelImagemLogin21Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIDVenda))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addGroup(painelImagemLogin21Layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addGap(53, 53, 53)
                        .addComponent(btSalvar)
                        .addGap(51, 51, 51)
                        .addComponent(btExcluir)
                        .addGap(49, 49, 49)
                        .addComponent(btSair)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelImagemLogin21Layout.setVerticalGroup(
            painelImagemLogin21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImagemLogin21Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(painelImagemLogin21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(painelImagemLogin21Layout.createSequentialGroup()
                        .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cbEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImagemLogin21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelImagemLogin21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSalvar)
                    .addComponent(btExcluir)
                    .addComponent(btSair))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemLogin21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemLogin21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            int valor = JOptionPane.showConfirmDialog(null, "Tem certeze que deseja salvar?", "Salvar edição", 1);
            if (valor == 0) {
                int tam = jTable1.getRowCount();
                for (int d = 0; d < tam; d++) {

                    String id = (String) jTable1.getValueAt(d, 0);
                    String quantidade = (String) jTable1.getValueAt(d, 1);
                    String val = (String) jTable1.getValueAt(d, 2);
                    String data = (String) jTable1.getValueAt(d, 3);
                    String produto = (String) jTable1.getValueAt(d, 4);
                    String funcionarios = (String) jTable1.getValueAt(d, 5);

                    if (verificar(val, quantidade, data, id)) {
                        List<Funcionario> lista = dao.pesquisar(funcionarios.trim());
                        List<Estoque> lista2 = dao2.pesquisar(produto.trim());

                        try {
                            SimpleDateFormat dat = new SimpleDateFormat("dd/MM/yyyy");
                            Calendar cal = Calendar.getInstance();
                            cal.setTime(dat.parse(data));
                            venda.setData(cal);//4

                        } catch (ParseException ee) {
                            System.out.println(ee);
                        }
                        venda.setValor(Double.parseDouble(val));
                        venda.setQuantidade(Integer.parseInt(quantidade));//  

                        System.out.println(id);

                        venda.setIdVendas(Integer.parseInt(id));//6

                        venda.setIdEstoque(lista2.get(0).getIdEstoque());//8
                        venda.setIdFuncionario(lista.get(0).getIdFuncionario());

                        dao3.altera(venda);
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro em gravar linha " + id);
                        break;
                    }
                }
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                JOptionPane.showMessageDialog(null, "Dados ja foram salvos");
            }
        } catch (HeadlessException r) {
        }
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        mostrarLista();

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int selRow = jTable1.getSelectedRow();
        String valor = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() >= 0) {
            dtm.removeRow(jTable1.getSelectedRow());
            jTable1.setModel(dtm);
            dao3.remove(Integer.parseInt(valor));
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        mostrarLista();
    }//GEN-LAST:event_btLimparActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        if (!nome.equals("Gerente")) {
            jTable1.setEnabled(false);
            this.btExcluir.setVisible(false);
            this.btSalvar.setVisible(false);
            mostrarLista();
        }
        mostrarLista();
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtIDVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDVendaKeyPressed
        estoques();
        funcionario();
        List<Venda> lista = dao3.pesquisar(this.txtIDVenda.getText());
        DefaultTableModel modelo2 = (DefaultTableModel) jTable1.getModel();
        modelo2.setNumRows(0);
        SimpleDateFormat DateFor = new SimpleDateFormat("dd/MM/yyyy");
        for (Venda pro : lista) {
            String stringDate = DateFor.format(pro.getData().getTime());
            funcionario = dao.getByID(pro.getIdFuncionario());
            estoque = dao2.getByID(pro.getIdEstoque());
            modelo2.addRow(
                    new Object[]{pro.getIdVendas().toString(),
                        pro.getQuantidade().toString(),
                        pro.getValor().toString(),
                        stringDate,
                        estoque.getNomeProduto(),
                        funcionario.getNome()
                    });
        }
    }//GEN-LAST:event_txtIDVendaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbEstoque;
    private javax.swing.JComboBox<String> cbFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private images.PainelImagemLogin2 painelImagemLogin21;
    private javax.swing.JTextField txtIDVenda;
    // End of variables declaration//GEN-END:variables
}
